# Generated by Django 4.0.6 on 2022-07-30 07:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('image1', versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/work/', verbose_name='Image')),
                ('image2', versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/work/', verbose_name='Image')),
                ('image3', versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/work/', verbose_name='Image')),
                ('image4', versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/work/', verbose_name='Image')),
                ('image5', versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/work/', verbose_name='Image')),
                ('details', models.TextField()),
                ('info', tinymce.models.HTMLField()),
                ('date', models.DateField(auto_now_add=True)),
                ('link', models.URLField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
            ],
            options={
                'verbose_name_plural': 'Works',
            },
        ),
    ]
