# Generated by Django 4.0.6 on 2022-07-30 08:06

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='image2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/work/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='works',
            name='image3',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/work/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='works',
            name='image4',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/work/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='works',
            name='image5',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/work/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='works',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
