# Generated by Django 4.0.6 on 2022-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_works_image2_alter_works_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
