# Generated by Django 4.0.6 on 2022-08-01 05:39

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_works_image5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='image2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=1, upload_to='images/work/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='works',
            name='image3',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=1, upload_to='images/work/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='works',
            name='image4',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/work/', verbose_name='Image'),
        ),
    ]
