# Generated by Django 4.0.6 on 2022-08-01 06:05

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_works_image2_alter_works_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='image2',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/work/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='works',
            name='image3',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/work/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='works',
            name='image4',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/work/', verbose_name='Image'),
        ),
    ]
